First scratch
afigor2701/neural_network pull request #1
Opened 2024-01-17 22:20 UTC by afigor2701

2024-01-20 14:29 UTC, DimaTrushin requested changes
Обрати внимание, что я делал комментарии единожды. Если есть похожие места, то надо исправлять по аналогии.

Я не нашел системы сборки и вообще единиц трансляции в коде. Добавь их и тут же проверяй, что код который ты пишешь компилируется. Потому что текущий код не компилируется из-за опечаток и отсутствия хотя бы тупых имплементаций для методов класса Layer и NerualNetwork.

2024-01-20 14:29 UTC, DimaTrushin commented on .gitignore
> +build/
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-01-20 14:29 UTC, DimaTrushin commented on src/activation_functions/activation_function.h
> +    virtual double Derivative(double x) const;
Эти методы НЕ должны быть виртуальными. У тебя все виртуальные методы спрятаны в имплементации внутри.

2024-01-20 14:29 UTC, DimaTrushin commented on src/activation_functions/activation_function.h
Я видел твой комментарий в тг и ответил. Предложенный тобой дизайн через указатели на функции это более правильное решение. Но я тем не менее откомментирую.

2024-01-20 14:29 UTC, DimaTrushin commented on src/activation_functions/activation_function.h
> +    TActivationFunction(const TFunction& function) : function_ptr_(std::make_unique<TConcept<Function>>(function)) {
Если хочешь перехватывать в общем виде данные, то надо писать так
```cpp
template <typename TFunction>
TActivationFunction(TFunction&& function)
  : function_ptr_(std::make_unique<TConcept<TFunction>>(std::forward<TFunction>(function)))
```
Так же у тебя тут опечатка Function вместо TFunction.

2024-01-20 14:29 UTC, DimaTrushin commented on src/activation_functions/activation_function.h
> +    public:
Тут надо добавить конструкторы два вида:
```cpp
TConcept(const TFunction& function) : function_(function) {};
TConcept(TFunction&& function) : function_(std::move(function)) {}
```
И еще убери T из названия. Потому что так обычно шаблонный параметр обозначают. Это очень путает.

2024-01-20 14:29 UTC, DimaTrushin commented on src/activation_functions/activation_function.h
> +        virtual double Evaluate(double x) const {
Тот должно быть не virtual, а overload

2024-01-20 14:29 UTC, DimaTrushin commented on src/activation_functions/activation_function.h
> +class TActivationFunction {
1) Для полной красоты не хватает виртуализации копирования.
2) Но действительно можно просто внутри хранить два указателя. Заведи только для них юзинги вида
```cpp
using Signature = double(double);
using FPtr = Signature*;
```
и потом храни
```cpp
FPtr f0_;
FPtr f1_;
```
или что-то в этом духе. Единственное в конструкторе везде предусмотри, чтобы указатели всегда были не нулевые. При копировании и муве это условие не нарушится.

2024-01-20 14:29 UTC, DimaTrushin commented on src/include_eigen.h
> +// TODO: выбрать, как лучше, чтобы вектора лежали в памяти. Видимо, придется идти по векторам
Это зависит от матрицы. Например градиенты u лучше положить по строкам и умножаться они будут на вектора справа и это будет лучше. А вот данные, которые сеть съедает лучше по столбцам. Потому хорошо бы иметь возможность и то и то иметь. Это прикольно, что ты единственный, кто об этом задумался =)

2024-01-20 14:29 UTC, DimaTrushin commented on src/activation_functions/activation_function.cpp
> +virtual double TActivationFunction::Evaluate(double x) const {
При определении функции не надо писать слово virtual. Оно не несет никакого смысла.

2024-01-20 14:29 UTC, DimaTrushin commented on src/layer.h
> +
Если создаешь класс с какими-то методами, то хотя бы делай для них тупую имплементацию, чтобы не было ошибок линковки.

2024-01-20 14:29 UTC, DimaTrushin commented on src/layer.h
> +class TLayer {
Я так понял, что по дизайну у тебя начальная буква класса T. Тогда надо у шаблонов параметры по-другому обозначать. Без буквы T и как-то по-другому.

2024-01-20 14:29 UTC, DimaTrushin commented on src/layer.h
> +    TLayer(size_t size, TActivationFunction function);
1) Не используй сырые типы. Так как ты используешь Eigen, у него есть Eigen::Index, который отвечает за тип размеров и индексов. Используй его в качестве юзинга.
2) Тебе на самом деле нужно два значения для слоя: размер входа и размер выхода.
3) Если принимаешь параметр by value не забудь потом его мувнуть внутрь.

2024-01-20 14:29 UTC, DimaTrushin commented on src/layer.h
> +    VectorXd gradient_for_b_;
Если уж ты хранишь поправки к градиентам внутри слоя, то тебе придется хранить батч на входе и батч градиентов пришедших. Либо ничего не хранить. Просто эти данные имеют смысл только внутри функции обучения.
С другой стороны правильный модульный дизайн походу получается, если все же хранить всю промежуточную инофрмацию. Но только тогда надо сделать два вида сети: сеть для обучения (хранит всю промежуточную информацию внутри), сеть для использования (хранит только настроенные параметры). И еще нужен метод конвертации первой ко второй.

2024-01-20 14:29 UTC, DimaTrushin commented on src/layer.h
> +    void AccumulateChangeWeights(const VectorXd& x, const VectorXd& u);
А что мешает сделать метод, который возвращает изменения весов?

2024-01-20 14:29 UTC, DimaTrushin commented on src/neural_network.h
> +template <typename TLossFunciton>
На надо LossFunction делать шаблонным параметром. Это глупо. Ты все параметры до этого передавал в run-time, а тут внезапно стал в compile-time передавать. Убрать и сделать как с ActivationFunction. Там так же придется хранить внутри два указателя.

2024-01-20 14:29 UTC, DimaTrushin commented on src/neural_network.h
> +                   TLossFunction loss_funciton);
Ты уверен, что хочешь хранить LossFunction в нейросети? Она же нужна только в момент обучения.

2024-01-20 14:29 UTC, DimaTrushin commented on src/neural_network.h
> +    TNeuralNetwork(const std::initializer_list<std::pair<size_t, TActivationFunction>>& layers,
Не используй std::pair, потому что пользователю не понятно, что значат first и second. Заведи struct с нужным именем и нужными названиями полей. И тогда пользователь сможет по нормальным названиям обращаться к элементам структуры.

2024-01-20 14:29 UTC, DimaTrushin commented on src/neural_network.h
> +    void Train(const MatrixXd& x, const MatrixXd& results);
Train должна принимать
1) обучающие данные (я так понимаю это твои x и results). Может тогда для единообразия сделать x и y.
2) размер батча
3) границу для Loss которую мы хотим достичь
4) максимальное количество эпох
5) алгоритм для градиентного спуска, но можно и просто начальный шаг и скорость его убывания.

2024-01-20 14:29 UTC, DimaTrushin commented on src/neural_network.h
> +template <typename TLossFunciton>
1) Если уж пишешь шаблоны, то для них все надо определять inline прямо в теле класса. Иначе у тебя слишком много будет шума по отношению к коду. У меня про это в мануале написано.
2) Тут тебе не нужны шаблоны. Убери шаблоны и помести код в cpp файл.

Вообще шаблоны -- это библиотечный код. А если ты пишешь конкретную нейросеть, то это признак плохого дизайна, если ты делаешь ее шаблонной. Либо уж тогда все компоненты должны быть собраны на шаблонах. Но у тебя все в run-time делается, так что так не надо делать.

2024-05-15 07:25 UTC, DimaTrushin requested changes
Я добавил еще несколько замечаний. Из критического, кажется у тебя не весь код в репозитории, в частности я не нашел mnist/mnist_reader.hpp.

Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

2024-05-15 07:25 UTC, DimaTrushin commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "-std=c++20")
Никогда НЕ пиши компиляторо зависимых флагов. Всегда оборачивай такие вещи в проверку на компилятор. Я например не смогу это собрать на msvc. Всегда пользуйся только портируемыми механизмами, учитывая, что cmake предоставляет тебе такой механизм
```cpp
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED True)
```

2024-05-15 07:25 UTC, DimaTrushin commented on README.md
Плохая инструкция. Тут надо более хитро делать. Во-первых, сама инструкция так себе. Во-вторых, это еще может не сработать. Надо рекурсивно проапдейтить и инициализировать все сабмодули. 
```
git submodule update --init --recursive
```

2024-05-15 07:25 UTC, DimaTrushin commented on src/utils/guard.h
> +class Guard {
Вот прям интересно зачем такое понадобилось.

2024-05-15 07:25 UTC, DimaTrushin commented on src/utils/random.h
> +private:
Не повторяй ключевые слова уровня доступа.

2024-05-15 07:25 UTC, DimaTrushin commented on src/utils/random.h
> +    static RandomGenerator& GetGenerator();
А как какать? Как ты будешь звать этот генератор, если никому его создать нельзя? Я что-то совсем не понимаю, что тут происходит.

2024-05-15 07:25 UTC, DimaTrushin commented on src/utils/random.h
> +    Eigen::Rand::P8_mt19937_64 urng{ 54 };
Не используй квалификаторы доступа пространства имен. Заведи юзинги.

2024-05-15 07:25 UTC, DimaTrushin commented on src/neural_network_builder.h
> +}  // namespace NNeuralNetwork
Добавь пустую строку в конце каждого файла. Дело в том, что гит на это ругается и пользователь твоего репозитория будет видеть сообщения об ошибках от гита. Не делай так.
Добавить в clang-format правило:
InsertNewlineAtEOF: true

2024-05-15 07:25 UTC, DimaTrushin commented on src/neural_network_builder.cpp
> +    activation_functions.push_back(function);
Сделай push_back(std::move(function)) раз принимаешь by value. Заведи себе за привычку, что если ты принимаешь данные по значению, то поглощай их следующим кодом.

2024-05-15 07:25 UTC, DimaTrushin commented on src/layer.cpp
> +    : A_(utils::RandomGenerator::GetRandomMatrix(out_size, in_size) / 20.0), b_(utils::RandomGenerator::GetRandomVector(out_size) / 20.0), function_(function) {
```cpp
function_(std::move(function))
```

2024-05-15 07:25 UTC, DimaTrushin commented on src/layer.cpp
> +    : A_(utils::RandomGenerator::GetRandomMatrix(out_size, in_size) / 20.0), b_(utils::RandomGenerator::GetRandomVector(out_size) / 20.0), function_(function) {
И еще мне не нравится магическая константа 20.0. Заведи хотя бы статическую константу с говорящим имененм.

2024-05-15 07:25 UTC, DimaTrushin commented on src/layer.cpp
> +    : A_(utils::RandomGenerator::GetRandomMatrix(out_size, in_size) / 20.0), b_(utils::RandomGenerator::GetRandomVector(out_size) / 20.0), function_(function) {
Заведи приватный using
```cpp
using Random = utils::RandomGenerator;
```
Тогда ты сможешь писать
```cpp
Random::GetRandomMatrix(...);
```
Обрати внимание, что слово Random тут встречается дважды, потому внутри случайного генератора НЕТ смысла добавлять слово Random в имена методов. Лучше добавить название распределения или просто оставить слово Matrix и все.

2024-05-15 07:25 UTC, DimaTrushin commented on src/activation_functions/sigmoid.cpp
> +    return 1.0L / (1.0L + exp(-x));
Нахрена тебе тут long double литерал, ты все равно потом до double режешь? Учитывая, что ниже в производной ты вообще используешь int. Что за неконсистентность?

2024-05-15 07:25 UTC, DimaTrushin commented on src/activation_functions/sigmoid.cpp
> +    return tmp / ((1 + tmp) * (1 + tmp));
Вот тут у тебя могут double взорваться в nan. При отрицательных x ты будешь делить очень большое на очень большое. Перепиши код так, чтобы не было деления большого на большое или малого на малое или чтобы не было умножения малого на большое. Во всех этих случаях взрывается точность вычислений и ты почти наверно получишь NaN-ы.

2024-05-15 07:25 UTC, DimaTrushin commented on src/activation_functions/activation_function.h
> +    TActivationFunction(TFunction) : evaluate_(TFunction::Evaluate), derivative_(TFunction::Derivative) {
А не лучше ли будет убрать вообще аргумент конструктора, чтобы звать код так
```cpp
TActivationFunction f = TActivationFunction<Sigmoid>();
```
Просто я не люблю переносить в run-time то, что делается в compile-time.

2024-05-15 07:25 UTC, DimaTrushin commented on src/activation_functions/activation_function.cpp
> +    for (Index i = 0; i < x.rows(); ++i) {
Это можно сделать в одну строку через unaryExpr. Дело в том, что Eigen этот цикл быстрее может реализовать.

2024-05-15 07:25 UTC, DimaTrushin commented on src/activation_functions/activation_function.cpp
> +    return evaluate_(x);
У тебя глобально не хватает assert-ов. Например тут я бы проверил, что указатель не нуль с помощью assert(evaluate_);

2024-05-15 07:25 UTC, DimaTrushin commented on examples/mnist_trainer.cpp
> +struct DataSet {
Если объявляешь класс, функцию или переменную в cpp файле, то это надо делать внутри anonymous namespace. Не забывай про это!

2024-05-15 07:25 UTC, DimaTrushin commented on examples/mnist_trainer.cpp
> +        result(static_cast<Index>(labels[i]), i) = 1.0;
Вместо каста ты бы лучше создал функцию с нормальным названием. Ты же тут явно делаешь конвертацию данных и имя функции бы сказало что к чему конвертируется.

2024-05-15 07:25 UTC, DimaTrushin commented on examples/mnist_trainer.cpp
> +#include "mnist/mnist_reader.hpp"
Я не вижу этой папки в проекте.

2024-05-15 07:25 UTC, DimaTrushin commented on examples/mnist_trainer.cpp
> +#include "mnist/mnist_reader.hpp"
Почему неконсистентные названия хедеров? Почему везде h, а тут hpp?

2024-05-15 07:25 UTC, DimaTrushin commented on examples/mnist_trainer.cpp
> +int main() {
У тебя не используются исключения в коде, но ты используешь сторонние библиотеки которые могут кидать исключения. И они у тебя не отключены при сборке. Потому надо защищать операционную систему от утечки исключений туда. Это делается так
```cpp
#include "Tests.h"
#include "Except.h"

int main() {
  try {
    nn::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```
Обрати внимание, что main не занимается никакой конкретной работой, она все делегируется другому коду. Ее задача заниматься оркестровкой на самом высоком уровне, даже исключения она делегирует обрабатывать другому коду. Не надо заниматься конкретной работой в main.

2024-05-15 07:25 UTC, DimaTrushin commented on src/training_layer.cpp
> +    last_in_ = x;
напиши
```cpp
last_in_ = std::move(x);
```
чтобы не делать лишнее копирование. Ты и так поглотил x раз принял его по значению. Но тогда надо поменятьместами эту строчку и следующую. Или в следующей x заменить на last_in_.

2024-05-15 07:25 UTC, DimaTrushin commented on src/training_layer.cpp
> +MatrixXd TTrainingLayer::PropagationAndCoeffUpdate(MatrixXd gradients) {
Ты нигде внутри этого метода не переиспользуешь память gradients если я не продолбался. А потому НЕТ смысла принимать его по значению. Принимай по константной ссылке иначе это лишнее копирование.

2024-05-15 07:25 UTC, DimaTrushin commented on src/neural_network.cpp
> +    return x(Eigen::indexing::all, Eigen::indexing::seq(start, std::min(x.cols() - 1, start + batch_size - 1)));
а не хочешь завести using, чтобы не писать Eigen::idexing?

2024-05-15 07:25 UTC, DimaTrushin commented on src/neural_network.cpp
> +std::vector<TLayer> MakeLayers(std::vector<TTrainingLayer>& training_layers) {
лучше Transform назвать, потому что ты по сути старые слои преобразуешь в новые ломая старые.

2024-05-15 07:25 UTC, DimaTrushin commented on src/neural_network.cpp
> +
Нарушение уровня абстракции. У тебя код до и после этого цикла на высоком уровне, а в цикле ты делаешь мелкую конкретную работу.

2024-05-15 07:25 UTC, DimaTrushin commented on src/neural_network.cpp
> +    layers_ = MakeTrainingLayers(GetLayers(), learning_rate); // TODO: make guard
Да, это прям очень хорошее замечание. В целом можно сделать через std::lock_guard. Но для этого тебе нужен объект "переключатель слоев", который захватывается этим lock_guard-ом.

2024-05-15 07:25 UTC, DimaTrushin commented on src/neural_network.cpp
> +double TNeuralNetwork::Epoch(const MatrixXd& x, const MatrixXd& y, Index batch_size, TLossFunction loss_function) {
плохо, что у тебя функция не имеет глагола в названии. Что она возвращает надо догадываться или читать код.

2024-05-15 07:25 UTC, DimaTrushin commented on src/neural_network.h
> +    double Epoch(const MatrixXd& x, const MatrixXd& y, Index batch_size, TLossFunction loss_function);
а тут почему loss_function передается by value?

2024-05-15 07:25 UTC, DimaTrushin commented on src/loss_functions/square_error.cpp
> +    return 2.0L * (x - y);
убери L

2024-05-15 07:25 UTC, DimaTrushin commented on src/loss_functions/loss_function.h
> +    // Скорее всего надо принимать Eigen::MatrixBase, чтобы избежать копирований, т.к. буду делать слайся матрицы
Ой там сложно.

2024-05-15 07:25 UTC, DimaTrushin commented on src/loss_functions/loss_function.cpp
> +            result(i, j) = derivative_x_(x(j, i), y(j, i));
А почему индексы поменяны местами справа? Выглядит так, как будто ты тут делаешь дополнительно транспонирование, а потом там где оно нужно будет в формулах, ты его опускаешь. Если так, то это ошибка.

2024-05-15 08:39 UTC, afigor2701 commented on src/neural_network.h
> +    double Epoch(const MatrixXd& x, const MatrixXd& y, Index batch_size, TLossFunction loss_function);
TLossFunction и TActivationFunction хранят по 2 указателя всего, т.е. весят по 16 байт. Поэтому я нигде не использую с ними std::move и ссылки, а передаю по значению

2024-05-15 08:41 UTC, afigor2701 commented on src/neural_network_builder.cpp
> +    activation_functions.push_back(function);
Просто TActivationFunction весит всего 16 байт(2 указателя), поэтому я и работаю с ним везде по значению. Мне несложно везде писать std::move, просто насколько это нужно в таких случаях?

2024-05-15 09:08 UTC, afigor2701 commented on src/activation_functions/sigmoid.cpp
> +    return tmp / ((1 + tmp) * (1 + tmp));
я попробовал это поменять. теперь у меня максимум деление 1/exp(-x) происходит. по идее это получше деления большого на большое.

2024-05-15 09:19 UTC, afigor2701 commented on examples/mnist_trainer.cpp
> +#include "mnist/mnist_reader.hpp"
Это сторонняя библиотека, я ее добавлял через include_directory. Сейчас я сделал все так, что теперь любой инклюд сторонней библиотеки обязательно имеет в пути third_party, чтобы сразу было понятно, что это сторонний код

2024-05-15 09:20 UTC, afigor2701 commented on examples/mnist_trainer.cpp
> +#include "mnist/mnist_reader.hpp"
Это сторонняя библиотека. Исправлено, что теперь в пути инклюда обязательно указывается third_party, чтобы человек сразу видел, что этот код сторонней библиотеки

2024-11-29 12:15 UTC, merged